# ---------------------------------------------------------------------------
# Global
# ---------------------------------------------------------------------------
variables:
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-smtp
  RELEASE_REGISTRY: docker.io
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  PYTEST_COV_MODULE: mo_smtp
  PYTEST_COV_FAIL_UNDER: 100
  PRECOMMIT_USE_POETRY: "true"

stages:
  - lint
  - test
  - coverage
  - build
  - release
  - deploy


# Conditions
#############
# Global Conditions
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
      variables:
        # Override the IMAGE_SHA variable on tag pipelines to avoid both the default
        # branch pipeline and tag pipeline overriding each other's images arbitrarily when
        # they are both running at the same time on master.
        IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  # See https://git.magenta.dk/labs/salt-automation/-/tree/master/gitlab-ci-templates/common

    # Runs linting
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/pre-commit.v1.yml

    # Runs testing
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/python/pytest.v1.yml

  # Includes til at køre config-updateren, se anvendelse længere nede
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/config-updater-meta.v1.yml

  # Kører build
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-build.v1.yml

  # Kører automatisk release
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-release.v1.yml

  # Conventional commits
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/conventional-commits.v1.yml


# Kører config-updater for dev. Kører på semantiske versioner
Deploy to Dev:
  extends: .release-to-dev
  needs: ["Build", "Release version"]
  variables:
    ENDPOINT: os2mo/salt/ldapimportexport/update-dev

# Kører config-updater for test. Kører kun scheduleret
Deploy to Test:
  extends: .release-to-test
  variables:
    ENDPOINT: os2mo/salt/ldapimportexport/update-test

# Kører config-updater for prod. Kører kun scheduleret
Deploy to Prod:
  extends: .release-to-prod
  variables:
    ENDPOINT: os2mo/salt/ldapimportexport/update-prod


