import datetime
from datetime import timezone, timedelta
from unittest.mock import AsyncMock
from unittest.mock import MagicMock
from uuid import uuid4

from mo_smtp.autogenerated_graphql_client.address_data import AddressDataAddresses
from mo_smtp.autogenerated_graphql_client.employee_data import EmployeeDataEmployees
from mo_smtp.autogenerated_graphql_client.employee_name import EmployeeNameEmployees
from mo_smtp.autogenerated_graphql_client.manager_data import ManagerDataManagers
from mo_smtp.autogenerated_graphql_client.institution_address import (
    InstitutionAddressOrgUnits,
)
from mo_smtp.autogenerated_graphql_client.org_unit_address import (
    OrgUnitAddressOrgUnits,
)
from mo_smtp.autogenerated_graphql_client.org_unit_ancestors import (
    OrgUnitAncestorsOrgUnits,
)
from mo_smtp.autogenerated_graphql_client.org_unit_data import OrgUnitDataOrgUnits
from mo_smtp.autogenerated_graphql_client.org_unit_relations import (
    OrgUnitRelationsOrgUnits,
)
from mo_smtp.autogenerated_graphql_client.ituser import (
    ItuserItusers,
    ItuserItusersObjectsCurrent,
)
from mo_smtp.autogenerated_graphql_client.related_unit_registrations import (
    RelatedUnitRegistrationsRelatedUnits,
)
from mo_smtp.autogenerated_graphql_client.rolebinding import RolebindingRolebindings

import pytest
from fastramqpi.context import Context
from structlog.testing import capture_logs

from mo_smtp.agents import alert_on_manager_removal, handle_org_unit
from mo_smtp.agents import handle_related_units
from mo_smtp.agents import inform_manager_on_employee_address_creation
from mo_smtp.agents import alert_on_rolebinding
from mo_smtp.agents import alert_on_ituser


@pytest.fixture
def dataloader() -> AsyncMock:
    return AsyncMock()


@pytest.fixture
def DataLoader(dataloader: AsyncMock) -> MagicMock:
    DataLoader = MagicMock()
    DataLoader.return_value = dataloader
    return DataLoader


@pytest.fixture
def email_client() -> MagicMock:
    return MagicMock()


@pytest.fixture
def context(dataloader: AsyncMock, email_client: MagicMock) -> Context:
    email_settings = MagicMock()
    email_settings.receivers = ["datagruppen@silkeborg.dk"]

    return Context(
        {
            "user_context": {
                "dataloader": dataloader,
                "email_client": email_client,
                "email_settings": email_settings,
            }
        }
    )


async def test_inform_manager_on_employee_address_creation_no_employee(
    context: Context,
):
    mo = AsyncMock()
    mo.address_data.return_value = AddressDataAddresses.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "value": "test@example.com",
                        "employee_uuid": None,
                        "address_type": {"scope": "EMAIL"},
                    }
                }
            ]
        }
    )

    with capture_logs() as cap_logs:
        await inform_manager_on_employee_address_creation(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "The address does not belong to an employee" in str(cap_logs)


async def test_inform_manager_on_employee_address_creation_not_email(
    context: Context,
) -> None:
    mo = AsyncMock()
    mo.address_data.return_value = AddressDataAddresses.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "value": "not_an_email",
                        "employee_uuid": uuid4(),
                        "address_type": {"scope": "PHONE"},
                    }
                }
            ]
        }
    )

    with capture_logs() as cap_logs:
        await inform_manager_on_employee_address_creation(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "The address type is not EMAIL" in str(cap_logs)


async def test_inform_manager_on_employee_address_creation(
    context: Context,
):
    employee_uuid = uuid4()
    mo = AsyncMock()
    mo.address_data.return_value = AddressDataAddresses.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "value": "test@example.com",
                        "employee_uuid": employee_uuid,
                        "address_type": {"scope": "EMAIL"},
                    }
                }
            ]
        }
    )

    mo.employee_data.return_value = EmployeeDataEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Mick Jagger",
                        "addresses": [
                            {"value": "test@example.com"},
                        ],
                        "engagements": [
                            {
                                "org_unit": [{"name": "Stones"}],
                                "managers": [
                                    {
                                        "person": [
                                            {
                                                "addresses": [
                                                    {"value": "manager@email.com"}
                                                ]
                                            }
                                        ]
                                    },
                                ],
                            }
                        ],
                    }
                }
            ]
        }
    )

    await inform_manager_on_employee_address_creation(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once_with(
        receiver={"test@example.com"},
        cc={"manager@email.com"},
        subject="Registrering i MO",
        body="Denne besked er sendt som bekræftelse på at Mick Jagger er registreret i Stones",
        texttype="plain",
    )


async def test_inform_manager_on_employee_address_creation_multiple_engagements(
    context: Context,
):
    employee_uuid = uuid4()
    mo = AsyncMock()
    mo.address_data.return_value = AddressDataAddresses.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "value": "test@example.com",
                        "employee_uuid": employee_uuid,
                        "address_type": {"scope": "EMAIL"},
                    }
                }
            ]
        }
    )

    mo.employee_data.return_value = EmployeeDataEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Mick Jagger",
                        "addresses": [
                            {"value": "test@example.com"},
                        ],
                        "engagements": [
                            {
                                "org_unit": [{"name": "Stones"}],
                                "managers": [
                                    {
                                        "person": [
                                            {
                                                "addresses": [
                                                    {"value": "manager@email.com"}
                                                ]
                                            }
                                        ]
                                    },
                                ],
                            },
                            {
                                "org_unit": [{"name": "Rolling"}],
                                "managers": [
                                    {
                                        "person": [
                                            {
                                                "addresses": [
                                                    {
                                                        "value": "another_manager@email.com"
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                ],
                            },
                        ],
                    }
                }
            ]
        }
    )

    await inform_manager_on_employee_address_creation(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once()

    called_args = email_client.send_email.call_args[
        1
    ]  # Get the keyword arguments passed to the function
    body = called_args["body"]

    # Need to check like this, since 'Rolling' and 'Stones' comes in random order, and therefore the test will fail 50% of the time
    # Ensure both 'Rolling' and 'Stones' are in the body, regardless of order
    assert "Rolling" and "Stones" in body, (
        f"Expected 'Rolling' and 'Stones' to be in body, but got {body}"
    )

    # Also check that the rest of the parameters are correct
    assert called_args["receiver"] == {"test@example.com"}
    assert called_args["cc"] == {"another_manager@email.com", "manager@email.com"}
    assert called_args["subject"] == "Registrering i MO"
    assert called_args["texttype"] == "plain"


async def test_alert_on_manager_removal_manager_not_found(context: Context):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj({"objects": []})
    with capture_logs() as cap_logs:
        await alert_on_manager_removal(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "Manager not found" in str(cap_logs)


async def test_alert_on_manager_removal_currently_employed(context: Context):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": uuid4(),
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": None,
                            },
                        }
                    ]
                }
            ]
        }
    )

    with capture_logs() as cap_logs:
        await alert_on_manager_removal(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "Manager is currently employed" in str(cap_logs)


async def test_alert_on_manager_removal_future_to_date(context: Context):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": uuid4(),
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": datetime.datetime(
                                    2090,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                            },
                        }
                    ]
                }
            ]
        }
    )

    with capture_logs() as cap_logs:
        await alert_on_manager_removal(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "to_date is in the future" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_alert_on_manager_removal_past_to_date(context: Context):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": uuid4(),
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": datetime.datetime(
                                    2000,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                            },
                        }
                    ]
                }
            ]
        }
    )

    mo.employee_name.return_value = EmployeeNameEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Mick Jagger",
                    }
                }
            ]
        }
    )
    mo.org_unit_data.return_value = OrgUnitDataOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Rolling",
                        "user_key": "123stones",
                        "managers": [],
                    }
                }
            ]
        }
    )
    mo.org_unit_ancestors.return_value = OrgUnitAncestorsOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "ancestors": [{"name": "Rolling"}],
                        "name": "Stones",
                    }
                },
            ]
        }
    )
    await alert_on_manager_removal(context, uuid4(), None, mo)
    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once()

    call_args = email_client.send_email.call_args_list[0]

    receiver, header, message, _ = call_args.args
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert header == "En medarbejder er blevet fjernet fra lederfanen"
    assert "123stones" in message
    assert "Mick Jagger" in message
    assert "Rolling / Stones" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_alert_on_manager_vacant(context: Context):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": None,
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": None,
                            },
                        }
                    ]
                }
            ]
        }
    )
    mo.employee_name.return_value = EmployeeNameEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "None",
                    }
                }
            ]
        }
    )
    mo.org_unit_data.return_value = OrgUnitDataOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Rolling",
                        "user_key": "123stones",
                        "managers": [],
                    }
                }
            ]
        }
    )
    mo.org_unit_ancestors.return_value = OrgUnitAncestorsOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "ancestors": [{"name": "Rolling"}],
                        "name": "Stones",
                    }
                },
            ]
        }
    )
    await alert_on_manager_removal(context, uuid4(), None, mo)
    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert header == "En medarbejder er blevet fjernet fra lederfanen"
    assert "123stones" in message
    assert "Vacant manager" in message
    assert "Rolling / Stones" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_alert_on_manager_send_to_org_unit_email(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": uuid4(),
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": datetime.datetime(
                                    2000,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                            },
                        }
                    ]
                }
            ]
        }
    )
    mo.employee_name.return_value = EmployeeNameEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Mick Jagger",
                    }
                }
            ]
        }
    )
    mo.org_unit_data.return_value = OrgUnitDataOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Rolling",
                        "user_key": "123stones",
                        "root": [{"uuid": uuid4()}],
                        "managers": [],
                    }
                }
            ]
        }
    )
    mo.org_unit_ancestors.return_value = OrgUnitAncestorsOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "ancestors": [{"name": "Rolling"}],
                        "name": "Stones",
                    }
                },
            ]
        }
    )

    mo.institution_address.return_value = InstitutionAddressOrgUnits.parse_obj(
        {"objects": [{"current": {"addresses": [{"value": "org_unit@email.com"}]}}]}
    )

    with monkeypatch.context() as con:
        con.setenv("ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS", "True")
        await alert_on_manager_removal(context, uuid4(), None, mo)
    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args
    assert receiver == {"org_unit@email.com"}
    assert header == "En medarbejder er blevet fjernet fra lederfanen"
    assert "123stones" in message
    assert "Mick Jagger" in message
    assert "Rolling / Stones" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_alert_on_manager_send_to_root_email(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    org_unit_uuid = uuid4()
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": uuid4(),
                            "org_unit_uuid": org_unit_uuid,
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": datetime.datetime(
                                    2000,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                            },
                        }
                    ]
                }
            ]
        }
    )
    mo.employee_name.return_value = EmployeeNameEmployees.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Mick Jagger",
                    }
                }
            ]
        }
    )
    mo.org_unit_data.return_value = OrgUnitDataOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "name": "Rolling",
                        "user_key": "123stones",
                        "root": [{"uuid": org_unit_uuid}],
                        "managers": [],
                    }
                }
            ]
        }
    )
    mo.org_unit_ancestors.return_value = OrgUnitAncestorsOrgUnits.parse_obj(
        {
            "objects": [
                {
                    "current": {
                        "ancestors": [{"name": "Rolling"}],
                        "name": "Stones",
                    }
                },
            ]
        }
    )

    mo.institution_address.return_value = InstitutionAddressOrgUnits.parse_obj(
        {"objects": [{"current": {"addresses": [{"value": "org_unit@email.com"}]}}]}
    )

    # Should pick `root@email.com` since org_unit_uuid and root is the same uuid
    mo.org_unit_address.return_value = OrgUnitAddressOrgUnits.parse_obj(
        {"objects": [{"current": {"addresses": [{"value": "root@email.com"}]}}]}
    )

    with monkeypatch.context() as con:
        con.setenv("ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS", "True")
        await alert_on_manager_removal(context, uuid4(), None, mo)
    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args
    assert receiver == {"root@email.com"}
    assert header == "En medarbejder er blevet fjernet fra lederfanen"
    assert "123stones" in message
    assert "Mick Jagger" in message
    assert "Rolling / Stones" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_not_found(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(uuid4()))
        mo = AsyncMock()

        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {"objects": []}
        )

        with capture_logs() as cap_logs:
            await handle_org_unit(context, uuid4(), None, mo)

        email_client = context["user_context"]["email_client"]
        email_client.send_email.assert_not_called()
        assert "Org unit not found" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_not_in_loenorganisation(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    root_loen_org = uuid4()
    root_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))

        mo = AsyncMock()
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "org-unit-name",
                            "root": [{"uuid": root_uuid}],
                            "engagements": [
                                {"uuid": uuid4()},
                            ],
                            "related_units": [{"org_units": []}],
                        },
                    }
                ]
            }
        )

        with capture_logs() as cap_logs:
            await handle_org_unit(context, uuid4(), None, mo)

        email_client = context["user_context"]["email_client"]
        email_client.send_email.assert_not_called()
        assert "Org unit is not in the Lønorganisation" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_has_external_relation(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    root_loen_org = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        org_unit_uuid = uuid4()

        mo = AsyncMock()
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "org-unit-name",
                            "root": [{"uuid": root_loen_org}],
                            "engagements": [
                                {"uuid": uuid4()},
                            ],
                            "related_units": [
                                {
                                    "org_units": [
                                        {
                                            "uuid": org_unit_uuid,
                                            "root": [{"uuid": root_loen_org}],
                                        },
                                        {
                                            "uuid": uuid4(),
                                            "root": [{"uuid": uuid4()}],
                                        },
                                    ]
                                }
                            ],
                        },
                    }
                ]
            }
        )

        with capture_logs() as cap_logs:
            await handle_org_unit(context, org_unit_uuid, None, mo)

        email_client = context["user_context"]["email_client"]
        email_client.send_email.assert_not_called()
        assert "Org unit has a relation outside of the Lønorganisation" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_sends_email(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    root_loen_org = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        con.setenv("ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS", "true")

        mo = AsyncMock()
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "org-unit-name",
                            "root": [{"uuid": root_loen_org}],
                            "engagements": [
                                {"uuid": uuid4()},
                            ],
                            "related_units": [],
                        },
                    }
                ]
            }
        )
        mo.institution_address.return_value = InstitutionAddressOrgUnits.parse_obj(
            {"objects": [{"current": {"addresses": [{"value": "test@example.com"}]}}]}
        )

        await handle_org_unit(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once_with(
        receiver={"test@example.com"},
        subject="Manglende relation i Lønorganisation",
        body="Denne besked er sendt som en påmindelse om at enheden: org-unit-name "
        "ikke er relateret til en enhed i Administrationsorganisationen.",
        texttype="plain",
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_sends_email_falls_back_to_receivers(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    root_loen_org = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))

        mo = AsyncMock()
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "org-unit-name",
                            "root": [{"uuid": root_loen_org}],
                            "engagements": [
                                {"uuid": uuid4()},
                            ],
                            "related_units": [],
                        },
                    }
                ]
            }
        )

        await handle_org_unit(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once_with(
        receiver={"datagruppen@silkeborg.dk"},
        subject="Manglende relation i Lønorganisation",
        body="Denne besked er sendt som en påmindelse om at enheden: org-unit-name "
        "ikke er relateret til en enhed i Administrationsorganisationen.",
        texttype="plain",
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_org_unit_sends_email_to_root(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    root_loen_org = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        con.setenv("ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS", "true")

        mo = AsyncMock()
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "org-unit-name",
                            "root": [{"uuid": root_loen_org}],
                            "engagements": [
                                {"uuid": uuid4()},
                            ],
                            "related_units": [],
                        },
                    }
                ]
            }
        )

        # root == uuid - use root email
        mo.org_unit_address.return_value = OrgUnitAddressOrgUnits.parse_obj(
            {"objects": [{"current": {"addresses": [{"value": "root@mail.com"}]}}]}
        )
        mo.institution_address.return_value = InstitutionAddressOrgUnits.parse_obj(
            {"objects": [{"current": {"addresses": [{"value": "test@example.com"}]}}]}
        )

        await handle_org_unit(context, root_loen_org, None, mo)

    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once_with(
        receiver={"root@mail.com"},
        subject="Manglende relation i Lønorganisation",
        body="Denne besked er sendt som en påmindelse om at enheden: org-unit-name "
        "ikke er relateret til en enhed i Administrationsorganisationen.",
        texttype="plain",
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_ituser_events_sends_email(context: Context) -> None:
    mo = AsyncMock()
    ituser_test_data = ItuserItusersObjectsCurrent.parse_obj(
        {
            "user_key": "ADUSER-123",
            "rolebindings": [
                {"role": [{"name": "admin", "uuid": uuid4()}]},
                {"role": [{"name": "user", "uuid": uuid4()}]},
            ],
            "person": [{"name": "Mick Jagger", "uuid": uuid4()}],
            "itsystem": {"name": "Active Directory", "uuid": uuid4()},
        }
    )

    mo.ituser.return_value = ItuserItusers.parse_obj(
        {"objects": [{"current": ituser_test_data}]}
    )
    await alert_on_ituser(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once()

    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args

    assert receiver == {"datagruppen@silkeborg.dk"}
    assert header == "En IT-bruger er blevet oprettet i MO"
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "admin" in message
    assert "user" in message
    assert "Mick Jagger" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_rolebinding_events_sends_email(context: Context) -> None:
    rolebinding_uuid = uuid4()
    ituser_test_data = ItuserItusersObjectsCurrent.parse_obj(
        {
            "user_key": "ADUSER-123",
            "rolebindings": [
                {"role": [{"name": "admin", "uuid": uuid4()}]},
                {"role": [{"name": "user", "uuid": uuid4()}]},
            ],
            "person": [{"name": "Mick Jagger", "uuid": uuid4()}],
            "itsystem": {"name": "Active Directory", "uuid": uuid4()},
        }
    )

    mo = AsyncMock()

    mo.rolebinding.return_value = RolebindingRolebindings.parse_obj(
        {"objects": [{"current": {"ituser": [{"uuid": uuid4()}]}}]}
    )

    mo.ituser.return_value = ItuserItusers.parse_obj(
        {"objects": [{"current": ituser_test_data}]}
    )
    await alert_on_rolebinding(context, rolebinding_uuid, None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once()

    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args

    assert receiver == {"datagruppen@silkeborg.dk"}
    assert header == "En IT-bruger er blevet oprettet i MO"
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "admin" in message
    assert "user" in message
    assert "Mick Jagger" in message


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_ituser_events_fails_when_identical(context: Context) -> None:
    mo = AsyncMock()
    ituser_uuid = uuid4()
    ituser_test_data = ItuserItusersObjectsCurrent.parse_obj(
        {
            "user_key": "ADUSER-123",
            "rolebindings": [
                {"role": [{"name": "admin", "uuid": uuid4()}]},
                {"role": [{"name": "user", "uuid": uuid4()}]},
            ],
            "person": [{"name": "Mick Jagger", "uuid": uuid4()}],
            "itsystem": {"name": "Active Directory", "uuid": uuid4()},
        }
    )

    mo.ituser.return_value = ItuserItusers.parse_obj(
        {"objects": [{"current": ituser_test_data}]}
    )
    await alert_on_ituser(context, ituser_uuid, None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_called_once()

    call_args = email_client.send_email.call_args_list[0]
    receiver, header, message, _ = call_args.args

    assert receiver == {"datagruppen@silkeborg.dk"}
    assert header == "En IT-bruger er blevet oprettet i MO"
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "admin" in message
    assert "user" in message
    assert "Mick Jagger" in message

    with capture_logs() as cap_logs:
        await alert_on_ituser(context, ituser_uuid, None, mo)

    assert "Email is identical to the previous. An email will not be sent" in str(
        cap_logs
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_alert_on_manager_org_unit_not_found(context: Context) -> None:
    mo = AsyncMock()
    mo.manager_data.return_value = ManagerDataManagers.parse_obj(
        {
            "objects": [
                {
                    "validities": [
                        {
                            "employee_uuid": None,
                            "org_unit_uuid": uuid4(),
                            "validity": {
                                "from": datetime.datetime(
                                    2015,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                                "to": datetime.datetime(
                                    2020,
                                    1,
                                    1,
                                    tzinfo=timezone(timedelta(hours=1)),
                                ),
                            },
                        }
                    ]
                }
            ]
        }
    )
    mo.employee_name.return_value = EmployeeNameEmployees.parse_obj({"objects": []})
    mo.org_unit_data.return_value = OrgUnitDataOrgUnits.parse_obj({"objects": []})
    with capture_logs() as cap_logs:
        await alert_on_manager_removal(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "Org unit is possibly terminated or doesn't exist." in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_ituser_events_ituser_not_found(context: Context) -> None:
    mo = AsyncMock()
    mo.ituser.return_value = ItuserItusers.parse_obj({"objects": []})

    with capture_logs() as cap_logs:
        await alert_on_ituser(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "IT-user is possibly terminated or doesn't exist." in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_ituser_events_ituser_default_userkey(context: Context) -> None:
    mo = AsyncMock()
    ituser_uuid = uuid4()
    ituser_test_data = ItuserItusersObjectsCurrent.parse_obj(
        {
            "user_key": "nanoq-brugernavn",
            "rolebindings": [
                {"role": [{"name": "admin", "uuid": uuid4()}]},
                {"role": [{"name": "user", "uuid": uuid4()}]},
            ],
            "person": [{"name": "Mick Jagger", "uuid": uuid4()}],
            "itsystem": {"name": "Active Directory", "uuid": uuid4()},
        }
    )

    mo.ituser.return_value = ItuserItusers.parse_obj(
        {"objects": [{"current": ituser_test_data}]}
    )
    await alert_on_ituser(context, ituser_uuid, None, mo)

    with capture_logs() as cap_logs:
        await alert_on_ituser(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "IT-user has default user_key 'nanoq-brugernavn'." in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_rolebinding_events_ituser_not_found(context: Context) -> None:
    mo = AsyncMock()
    mo.rolebinding.return_value = RolebindingRolebindings.parse_obj(
        {"objects": [{"current": None}]}
    )
    mo.ituser.return_value = ItuserItusers.parse_obj({"objects": []})

    with capture_logs() as cap_logs:
        await alert_on_rolebinding(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "IT-user is possibly terminated or doesn't exist." in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_rolebinding_events_ituser_default_userkey(context: Context) -> None:
    rolebinding_uuid = uuid4()
    ituser_test_data = ItuserItusersObjectsCurrent.parse_obj(
        {
            "user_key": "nanoq-brugernavn",
            "rolebindings": [
                {"role": [{"name": "admin", "uuid": uuid4()}]},
                {"role": [{"name": "user", "uuid": uuid4()}]},
            ],
            "person": [{"name": "Mick Jagger", "uuid": uuid4()}],
            "itsystem": {"name": "Active Directory", "uuid": uuid4()},
        }
    )

    mo = AsyncMock()

    mo.rolebinding.return_value = RolebindingRolebindings.parse_obj(
        {"objects": [{"current": {"ituser": [{"uuid": uuid4()}]}}]}
    )

    mo.ituser.return_value = ItuserItusers.parse_obj(
        {"objects": [{"current": ituser_test_data}]}
    )

    with capture_logs() as cap_logs:
        await alert_on_rolebinding(context, rolebinding_uuid, None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "IT-user has default user_key 'nanoq-brugernavn'." in str(cap_logs)


# =====================================================================
# Tests for handle_related_units
# =====================================================================


def _make_registration_response(org_unit_uuids: list):
    """Helper to build the related_unit_registrations mock response."""
    return RelatedUnitRegistrationsRelatedUnits.parse_obj(
        {
            "objects": [
                {
                    "registrations": [
                        {
                            "validities": [
                                {
                                    "org_units_response": {
                                        "objects": [
                                            {"uuid": uid, "current": current}
                                            for uid, current in org_unit_uuids
                                        ]
                                    }
                                }
                            ],
                        }
                    ]
                }
            ]
        }
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_not_found(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(uuid4()))
        mo = AsyncMock()

        mo.related_unit_registrations.return_value = (
            RelatedUnitRegistrationsRelatedUnits.parse_obj({"objects": []})
        )

        with capture_logs() as cap_logs:
            await handle_related_units(context, uuid4(), None, mo)

        email_client = context["user_context"]["email_client"]
        email_client.send_email.assert_not_called()
        assert "Related units not found" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_org_unit_not_in_loenorg(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    """If the related_units only contains org_units outside the lønorg, no email."""
    root_loen_org = uuid4()
    other_root = uuid4()
    org_unit_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        mo = AsyncMock()

        mo.related_unit_registrations.return_value = _make_registration_response(
            [(org_unit_uuid, {"root": [{"uuid": other_root}]})]
        )

        # The helper will be called but the org unit is not in lønorg
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "Adm-enhed",
                            "root": [{"uuid": other_root}],
                            "engagements": [{"uuid": uuid4()}],
                            "related_units": [],
                        },
                    }
                ]
            }
        )

        with capture_logs() as cap_logs:
            await handle_related_units(context, uuid4(), None, mo)

        email_client = context["user_context"]["email_client"]
        email_client.send_email.assert_not_called()
        assert "Org unit is not in the Lønorganisation" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_sends_email(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    """When a related_units change leaves a lønorg unit without an adm relation,
    an email should be sent."""
    root_loen_org = uuid4()
    adm_root = uuid4()
    loen_org_unit_uuid = uuid4()
    adm_org_unit_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        con.setenv("ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS", "true")
        mo = AsyncMock()

        mo.related_unit_registrations.return_value = _make_registration_response(
            [
                (loen_org_unit_uuid, {"root": [{"uuid": root_loen_org}]}),
                (adm_org_unit_uuid, {"root": [{"uuid": adm_root}]}),
            ]
        )

        # Return different data depending on which org unit is queried
        def org_unit_relations_side_effect(uuid):
            if uuid == loen_org_unit_uuid:
                return OrgUnitRelationsOrgUnits.parse_obj(
                    {
                        "objects": [
                            {
                                "current": {
                                    "name": "Løn-enhed",
                                    "root": [{"uuid": root_loen_org}],
                                    "engagements": [{"uuid": uuid4()}],
                                    "related_units": [],
                                },
                            }
                        ]
                    }
                )
            return OrgUnitRelationsOrgUnits.parse_obj(
                {
                    "objects": [
                        {
                            "current": {
                                "name": "Adm-enhed",
                                "root": [{"uuid": adm_root}],
                                "engagements": [{"uuid": uuid4()}],
                                "related_units": [],
                            },
                        }
                    ]
                }
            )

        mo.org_unit_relations.side_effect = org_unit_relations_side_effect
        mo.institution_address.return_value = InstitutionAddressOrgUnits.parse_obj(
            {"objects": [{"current": {"addresses": [{"value": "test@example.com"}]}}]}
        )

        await handle_related_units(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]

    email_client.send_email.assert_called_once_with(
        receiver={"test@example.com"},
        subject="Manglende relation i Lønorganisation",
        body="Denne besked er sendt som en påmindelse om at enheden: Løn-enhed "
        "ikke er relateret til en enhed i Administrationsorganisationen.",
        texttype="plain",
    )


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_has_relation(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    """When the lønorg unit still has a valid adm relation, no email is sent."""
    root_loen_org = uuid4()
    adm_root = uuid4()
    loen_org_unit_uuid = uuid4()
    adm_org_unit_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        mo = AsyncMock()

        mo.related_unit_registrations.return_value = _make_registration_response(
            [
                (loen_org_unit_uuid, {"root": [{"uuid": root_loen_org}]}),
                (adm_org_unit_uuid, {"root": [{"uuid": adm_root}]}),
            ]
        )

        def org_unit_relations_side_effect(uuid):
            if uuid == loen_org_unit_uuid:
                return OrgUnitRelationsOrgUnits.parse_obj(
                    {
                        "objects": [
                            {
                                "current": {
                                    "name": "Løn-enhed",
                                    "root": [{"uuid": root_loen_org}],
                                    "engagements": [{"uuid": uuid4()}],
                                    "related_units": [
                                        {
                                            "org_units": [
                                                {
                                                    "uuid": loen_org_unit_uuid,
                                                    "root": [{"uuid": root_loen_org}],
                                                },
                                                {
                                                    "uuid": adm_org_unit_uuid,
                                                    "root": [{"uuid": adm_root}],
                                                },
                                            ]
                                        }
                                    ],
                                },
                            }
                        ]
                    }
                )
            return OrgUnitRelationsOrgUnits.parse_obj(
                {
                    "objects": [
                        {
                            "current": {
                                "name": "Adm-enhed",
                                "root": [{"uuid": adm_root}],
                                "engagements": [{"uuid": uuid4()}],
                                "related_units": [],
                            },
                        }
                    ]
                }
            )

        mo.org_unit_relations.side_effect = org_unit_relations_side_effect

        await handle_related_units(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_terminated_org_unit(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    """When an org unit does not exist in current (terminated or future-dated),
    the helper handles it via the org_unit_relations lookup."""
    root_loen_org = uuid4()
    terminated_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        mo = AsyncMock()

        mo.related_unit_registrations.return_value = _make_registration_response(
            [(terminated_uuid, None)]
        )

        # The org unit is not found (terminated)
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {"objects": []}
        )

        with capture_logs() as cap_logs:
            await handle_related_units(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "Org unit not found" in str(cap_logs)


@pytest.mark.usefixtures("minimal_valid_settings")
async def test_handle_related_units_org_unit_changed_root(
    context: Context, monkeypatch: pytest.MonkeyPatch
):
    """When an org unit was historically in the lønorg but has since changed root,
    the helper should skip it based on its current root."""
    root_loen_org = uuid4()
    new_root = uuid4()
    moved_org_unit_uuid = uuid4()

    with monkeypatch.context() as con:
        con.setenv("ROOT_LOEN_ORG", str(root_loen_org))
        mo = AsyncMock()

        # Registration still references the org unit (historical data)
        mo.related_unit_registrations.return_value = _make_registration_response(
            [(moved_org_unit_uuid, {"root": [{"uuid": root_loen_org}]})]
        )

        # But the org unit's current root is different (it moved)
        mo.org_unit_relations.return_value = OrgUnitRelationsOrgUnits.parse_obj(
            {
                "objects": [
                    {
                        "current": {
                            "name": "Flyttet-enhed",
                            "root": [{"uuid": new_root}],
                            "engagements": [{"uuid": uuid4()}],
                            "related_units": [],
                        },
                    }
                ]
            }
        )

        with capture_logs() as cap_logs:
            await handle_related_units(context, uuid4(), None, mo)

    email_client = context["user_context"]["email_client"]
    email_client.send_email.assert_not_called()
    assert "Org unit is not in the Lønorganisation" in str(cap_logs)
