from uuid import uuid4
import pytest

from freezegun import freeze_time

from mo_smtp.helpers import extract_current_or_latest_validity
from mo_smtp.autogenerated_graphql_client.manager_data import (
    ManagerDataManagersObjectsValidities,
)


@pytest.mark.parametrize(
    "validities, expected_uuid",
    [
        # One of the objects is valid today - return it
        (
            [
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-01T00:00:00+02:00",
                            "to": "2022-08-01T00:00:00+02:00",
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
                (
                    obj2 := ManagerDataManagersObjectsValidities.parse_obj(
                        {
                            "validity": {
                                "from": "2022-08-02T00:00:00+02:00",
                                "to": "2022-08-15T00:00:00+02:00",
                            },
                            "org_unit_uuid": uuid4(),
                        }
                    )
                ),
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-15T00:00:00+02:00",
                            "to": None,
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
            ],
            obj2.org_unit_uuid,
        ),
        # One of the objects is valid today (without to-date) - return it
        (
            [
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-01T00:00:00+02:00",
                            "to": "2022-08-02T00:00:00+02:00",
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
                (
                    obj2 := ManagerDataManagersObjectsValidities.parse_obj(
                        {
                            "validity": {
                                "from": "2022-08-02T00:00:00+02:00",
                                "to": None,
                            },
                            "org_unit_uuid": uuid4(),
                        }
                    )
                ),
            ],
            obj2.org_unit_uuid,
        ),
        # One of the objects is valid today - return it
        (
            [
                (
                    obj1 := ManagerDataManagersObjectsValidities.parse_obj(
                        {
                            "validity": {
                                "from": "2022-08-01T00:00:00+02:00",
                                "to": "2022-08-15T00:00:00+02:00",
                            },
                            "org_unit_uuid": uuid4(),
                        }
                    )
                ),
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-15T00:00:00+02:00",
                            "to": None,
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
            ],
            obj1.org_unit_uuid,
        ),
        # No object is valid today - return the latest
        (
            [
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-01T00:00:00+02:00",
                            "to": "2022-08-02T00:00:00+02:00",
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
                (
                    obj2 := ManagerDataManagersObjectsValidities.parse_obj(
                        {
                            "validity": {
                                "from": "2022-08-15T00:00:00+02:00",
                                "to": None,
                            },
                            "org_unit_uuid": uuid4(),
                        }
                    )
                ),
            ],
            obj2.org_unit_uuid,
        ),
        # No object is valid today - return the latest
        (
            [
                ManagerDataManagersObjectsValidities.parse_obj(
                    {
                        "validity": {
                            "from": "2022-08-01T00:00:00+02:00",
                            "to": "2022-08-02T00:00:00+02:00",
                        },
                        "org_unit_uuid": uuid4(),
                    }
                ),
                (
                    obj2 := ManagerDataManagersObjectsValidities.parse_obj(
                        {
                            "validity": {
                                "from": "2022-08-15T00:00:00+02:00",
                                "to": "2022-08-20T00:00:00+02:00",
                            },
                            "org_unit_uuid": uuid4(),
                        }
                    )
                ),
            ],
            obj2.org_unit_uuid,
        ),
    ],
)
@freeze_time("2022-08-10")
def test_extract_latest_object(validities, expected_uuid):
    assert extract_current_or_latest_validity(validities).org_unit_uuid == expected_uuid


def test_extract_latest_object_empty():
    result = extract_current_or_latest_validity([])
    assert result is None
