from collections.abc import AsyncIterator
from unittest.mock import MagicMock, patch
from uuid import UUID, uuid4

import pytest
from asgi_lifespan import LifespanManager  # type: ignore[import-not-found]
from asgi_lifespan._types import ASGIApp  # type: ignore[import-not-found]
from fastapi import FastAPI
from pytest import MonkeyPatch
from sqlalchemy.ext.asyncio import AsyncSession

from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.smtp_agent import create_app


@pytest.fixture
def root_loen_org() -> UUID:
    return uuid4()


@pytest.fixture
async def _app(
    monkeypatch: MonkeyPatch,
    root_loen_org: UUID,
) -> FastAPI:
    monkeypatch.setenv("SENDER", "test@example.dk")
    monkeypatch.setenv("RECEIVERS", '["datagruppen@silkeborg.dk"]')
    monkeypatch.setenv("SMTP_PORT", "1025")
    monkeypatch.setenv("SMTP_HOST", "mailcatcher")
    monkeypatch.setenv("SMTP_SECURITY", "none")
    monkeypatch.setenv("DRY_RUN", "True")
    monkeypatch.setenv("ACTIVE_AGENTS", "[]")
    monkeypatch.setenv("ROOT_LOEN_ORG", str(root_loen_org))

    with patch("mo_smtp.smtp_agent.EmailClient") as mock_email_cls:
        mock_email_cls.return_value = MagicMock()
        app = create_app()
    return app


@pytest.fixture
async def asgiapp(_app: FastAPI) -> AsyncIterator[ASGIApp]:
    """ASGI app with lifespan run."""
    async with LifespanManager(_app) as manager:
        yield manager.app


@pytest.fixture
async def app(_app: FastAPI, asgiapp: ASGIApp) -> FastAPI:
    """FastAPI app with lifespan run."""
    return _app


@pytest.fixture
async def graphql_client(app: FastAPI) -> GraphQLClient:
    """Authenticated GraphQL codegen client for OS2mo."""
    return app.state.context["graphql_client"]


@pytest.fixture
async def session(app: FastAPI) -> AsyncIterator[AsyncSession]:
    """Shared database session for tests that call handlers directly.

    Using a single open transaction means subsequent handler calls see
    pending writes from earlier calls — matching the dedup behavior a
    production session would give us after the DI wrapper commits."""
    sessionmaker = app.state.context["sessionmaker"]
    async with sessionmaker() as s, s.begin():
        yield s


@pytest.fixture
def email_client(app: FastAPI) -> MagicMock:
    return app.state.context["user_context"]["email_client"]


@pytest.fixture
def context(app: FastAPI):
    """Context dict matching what FastRAMQPI provides to handlers."""
    return app.state.context
