"""Integration tests for the org unit relation alert flow (handle_org_unit)."""

from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from mo_smtp.agents import handle_org_unit
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_nonexistent_org_unit_no_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the org unit UUID doesn't exist, no email is sent."""
    await handle_org_unit(context, uuid4(), None, graphql_client)
    email_client.send_email.assert_not_called()
