"""Integration tests for alert_on_manager_removal."""

from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from mo_smtp.agents import alert_on_manager_removal
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_manager_not_found(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the manager UUID doesn't exist, no email is sent."""
    await alert_on_manager_removal(context, uuid4(), None, graphql_client)
    email_client.send_email.assert_not_called()
