"""Integration tests for alert_on_ituser and alert_on_rolebinding."""

from datetime import datetime

import pytest
from unittest.mock import MagicMock
from uuid import UUID, uuid4

from sqlalchemy.ext.asyncio import AsyncSession

from mo_smtp.agents import alert_on_ituser, alert_on_rolebinding
from mo_smtp.autogenerated_graphql_client import GraphQLClient


async def _setup_ituser(
    graphql_client: GraphQLClient,
    root_uuid: UUID,
    user_key: str = "ADUSER-123",
) -> tuple[UUID, UUID]:
    """Create org unit, employee, IT system, engagement, role, rolebinding, and IT user.
    Returns (ituser_uuid, rolebinding_uuid)."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _engagement_result = (await graphql_client._testing__get_engagement_type()).objects[
        0
    ]
    assert _engagement_result.current is not None
    engagement_type = _engagement_result.current.classes[0].uuid
    _job_result = (await graphql_client._testing__get_job_function()).objects[0]
    assert _job_result.current is not None
    job_function = _job_result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    org_unit = await graphql_client._testing__create_org_unit(
        name="IT-afdeling",
        parent=root_uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )
    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    await graphql_client._testing__create_engagement(
        orgunit=org_unit.uuid,
        person=employee.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        from_=datetime(2010, 1, 1),
    )
    itsystem = await graphql_client._testing__create_it_system(
        name="Active Directory",
        from_=datetime(2010, 1, 1),
    )
    ituser = await graphql_client._testing__create_it_user(
        itsystem=itsystem.uuid,
        person=employee.uuid,
        name=user_key,
        from_=datetime(2010, 1, 1),
        engagements=None,
    )

    role_facet = (await graphql_client._testing__get_role_facet()).objects[0].uuid
    role = await graphql_client._testing__create_class(
        name="admin",
        facet_uuid=role_facet,
        from_=datetime(2010, 1, 1),
    )
    rolebinding = await graphql_client._testing__create_rolebinding(
        ituser=ituser.uuid,
        role=role.uuid,
        from_=datetime(2010, 1, 1),
    )

    return ituser.uuid, rolebinding.uuid


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_ituser_sends_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """An IT user event triggers an alert email."""
    ituser_uuid, _ = await _setup_ituser(graphql_client, root_loen_org)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    receiver = call_args.kwargs["receiver"]
    message = call_args.kwargs["body"]
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "Mick Jagger" in message


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_rolebinding_sends_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """A rolebinding event resolves to the IT user and sends an alert."""
    _, rolebinding_uuid = await _setup_ituser(graphql_client, root_loen_org)

    await alert_on_rolebinding(context, rolebinding_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    message = call_args.kwargs["body"]
    assert "Active Directory" in message
    assert "ADUSER-123" in message


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_ituser_dedup_identical_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """Sending the same ituser event twice should only produce one email."""
    ituser_uuid, _ = await _setup_ituser(graphql_client, root_loen_org)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_ituser_not_found(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the ituser UUID doesn't exist, no email is sent."""
    await alert_on_ituser(context, uuid4(), None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_ituser_default_userkey_is_skipped(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """IT users with the default user_key 'nanoq-brugernavn' are skipped."""
    ituser_uuid, _ = await _setup_ituser(
        graphql_client, root_loen_org, user_key="nanoq-brugernavn"
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_rolebinding_not_found(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the rolebinding UUID doesn't exist, no email is sent."""
    await alert_on_rolebinding(context, uuid4(), None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "false"})
async def test_ituser_content_hash_update_sends_second_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the data changes (new rolebinding added), the content hash differs
    and a second email is sent even though the ituser UUID is the same."""
    ituser_uuid, _ = await _setup_ituser(graphql_client, root_loen_org)

    # First call: sends email and stores the content hash
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    assert email_client.send_email.call_count == 1

    # Flush the session so the SentAlert row is visible to the next call
    await session.flush()

    # Add a second rolebinding with a different role, changing the content
    role_facet = (await graphql_client._testing__get_role_facet()).objects[0].uuid
    new_role = await graphql_client._testing__create_class(
        name="superadmin",
        facet_uuid=role_facet,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_rolebinding(
        ituser=ituser_uuid,
        role=new_role.uuid,
        from_=datetime(2010, 1, 1),
    )

    # Second call: content changed, so a new email should be sent
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    assert email_client.send_email.call_count == 2
