"""Integration tests for inform_manager_on_employee_address_creation."""

from datetime import datetime
from unittest.mock import MagicMock
from uuid import UUID, uuid4

import pytest

from mo_smtp.agents import inform_manager_on_employee_address_creation
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_org_unit_address_is_ignored(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the address belongs to an org unit (not an employee), no email is sent."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _result = (
        await graphql_client._testing__get_org_unit_address_type()
    ).objects[0]
    assert _result.current is not None
    org_unit_address_type = _result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    addr = await graphql_client._testing__create_org_unit_address(
        org_unit=root_loen_org,
        value="org@example.com",
        address_type=org_unit_address_type,
        from_=datetime(2010, 1, 1),
    )

    await inform_manager_on_employee_address_creation(
        context, addr.uuid, None, graphql_client
    )
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_no_address(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the address UUID doesn't exist, no email is sent."""
    await inform_manager_on_employee_address_creation(
        context, uuid4(), None, graphql_client
    )
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_employee_with_multiple_emails_is_skipped(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When an employee already has a previous email, no notification is sent."""
    _email_result = (await graphql_client._testing__get_email_address_type()).objects[0]
    assert _email_result.current is not None
    email_address_type = _email_result.current.classes[0].uuid

    employee = await graphql_client._testing__create_employee(
        first_name="Test", last_name="Person"
    )

    addr1 = await graphql_client._testing__create_address(
        person=employee.uuid,
        value="first@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_address(
        person=employee.uuid,
        value="second@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )

    await inform_manager_on_employee_address_creation(
        context, addr1.uuid, None, graphql_client
    )
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_sends_email_no_engagements(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """Employee with one email and no engagements gets a basic notification."""
    _email_result = (
        await graphql_client._testing__get_email_address_type()
    ).objects[0]
    assert _email_result.current is not None
    email_address_type = _email_result.current.classes[0].uuid

    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )

    addr = await graphql_client._testing__create_address(
        person=employee.uuid,
        value="mick@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )

    await inform_manager_on_employee_address_creation(
        context, addr.uuid, None, graphql_client
    )

    email_client.send_email.assert_called_once_with(
        receiver={"mick@example.com"},
        subject="Registrering i MO",
        body="Denne besked er sendt som bekræftelse på at Mick Jagger er registreret i OS2MO.",
        texttype="plain",
    )


@pytest.mark.integration_test
async def test_sends_email_with_engagement_and_manager_cc(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """Employee with engagement gets notification mentioning the org unit,
    and the manager is CC'd."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _email_result = (
        await graphql_client._testing__get_email_address_type()
    ).objects[0]
    assert _email_result.current is not None
    email_address_type = _email_result.current.classes[0].uuid
    _engagement_result = (
        await graphql_client._testing__get_engagement_type()
    ).objects[0]
    assert _engagement_result.current is not None
    engagement_type = _engagement_result.current.classes[0].uuid
    _job_result = (await graphql_client._testing__get_job_function()).objects[0]
    assert _job_result.current is not None
    job_function = _job_result.current.classes[0].uuid
    manager_level = (
        await graphql_client._testing__get_manager_level()
    ).objects[0].uuid
    manager_type = (
        await graphql_client._testing__get_manager_type()
    ).objects[0].uuid
    manager_responsibility = (
        await graphql_client._testing__get_manager_responsibility()
    ).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    org_unit = await graphql_client._testing__create_org_unit(
        name="Stones",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    manager = await graphql_client._testing__create_employee(
        first_name="Keith", last_name="Richards"
    )
    await graphql_client._testing__create_address(
        person=manager.uuid,
        value="keith@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_manager(
        orgunit=org_unit.uuid,
        person=manager.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=manager_responsibility,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    addr = await graphql_client._testing__create_address(
        person=employee.uuid,
        value="mick@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_engagement(
        orgunit=org_unit.uuid,
        person=employee.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        from_=datetime(2010, 1, 1),
    )

    await inform_manager_on_employee_address_creation(
        context, addr.uuid, None, graphql_client
    )

    email_client.send_email.assert_called_once_with(
        receiver={"mick@example.com"},
        cc={"keith@example.com"},
        subject="Registrering i MO",
        body="Denne besked er sendt som bekræftelse på at Mick Jagger er registreret i Stones",
        texttype="plain",
    )


@pytest.mark.integration_test
async def test_sends_email_with_multiple_engagements(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """Employee with 2 engagements in different org units gets a notification
    mentioning both units via 'de følgende enheder'."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _email_result = (
        await graphql_client._testing__get_email_address_type()
    ).objects[0]
    assert _email_result.current is not None
    email_address_type = _email_result.current.classes[0].uuid
    _engagement_result = (
        await graphql_client._testing__get_engagement_type()
    ).objects[0]
    assert _engagement_result.current is not None
    engagement_type = _engagement_result.current.classes[0].uuid
    _job_result = (await graphql_client._testing__get_job_function()).objects[0]
    assert _job_result.current is not None
    job_function = _job_result.current.classes[0].uuid
    manager_level = (
        await graphql_client._testing__get_manager_level()
    ).objects[0].uuid
    manager_type = (
        await graphql_client._testing__get_manager_type()
    ).objects[0].uuid
    manager_responsibility = (
        await graphql_client._testing__get_manager_responsibility()
    ).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    org_unit_a = await graphql_client._testing__create_org_unit(
        name="Guitars",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )
    org_unit_b = await graphql_client._testing__create_org_unit(
        name="Vocals",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    manager_a = await graphql_client._testing__create_employee(
        first_name="Keith", last_name="Richards"
    )
    await graphql_client._testing__create_address(
        person=manager_a.uuid,
        value="keith@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_manager(
        orgunit=org_unit_a.uuid,
        person=manager_a.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=manager_responsibility,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    manager_b = await graphql_client._testing__create_employee(
        first_name="Charlie", last_name="Watts"
    )
    await graphql_client._testing__create_address(
        person=manager_b.uuid,
        value="charlie@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_manager(
        orgunit=org_unit_b.uuid,
        person=manager_b.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=manager_responsibility,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    addr = await graphql_client._testing__create_address(
        person=employee.uuid,
        value="mick@example.com",
        address_type=email_address_type,
        from_=datetime(2010, 1, 1),
    )

    await graphql_client._testing__create_engagement(
        orgunit=org_unit_a.uuid,
        person=employee.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_engagement(
        orgunit=org_unit_b.uuid,
        person=employee.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        from_=datetime(2010, 1, 1),
    )

    await inform_manager_on_employee_address_creation(
        context, addr.uuid, None, graphql_client
    )

    email_client.send_email.assert_called_once()
    call_kwargs = email_client.send_email.call_args.kwargs
    assert call_kwargs["receiver"] == {"mick@example.com"}
    assert call_kwargs["cc"] == {"keith@example.com", "charlie@example.com"}
    assert call_kwargs["subject"] == "Registrering i MO"
    assert call_kwargs["texttype"] == "plain"
    body = call_kwargs["body"]
    assert "de følgende enheder" in body
    assert "Guitars" in body
    assert "Vocals" in body
