"""Integration tests for alert_on_manager_removal."""

from datetime import datetime
from unittest.mock import MagicMock
from uuid import UUID, uuid4

import pytest

from mo_smtp.agents import alert_on_manager_removal
from mo_smtp.autogenerated_graphql_client import GraphQLClient


async def _setup_org_and_employee(
    graphql_client: GraphQLClient, root_uuid: UUID
) -> tuple[UUID, UUID]:
    """Create a root org unit, a child org unit, and an employee.

    Returns (org_unit_uuid, employee_uuid).
    """
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    org_unit = await graphql_client._testing__create_org_unit(
        name="Afdeling",
        parent=root_uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )
    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    return org_unit.uuid, employee.uuid


@pytest.mark.integration_test
async def test_manager_not_found(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the manager UUID doesn't exist, no email is sent."""
    await alert_on_manager_removal(context, uuid4(), None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_currently_employed_manager_no_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """A manager with no to_date and an employee is currently employed — no email."""
    org_unit_uuid, employee_uuid = await _setup_org_and_employee(
        graphql_client, root_loen_org
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee_uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=None,
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_terminated_manager_past_to_date_sends_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """A manager terminated in the past triggers an alert email."""
    org_unit_uuid, employee_uuid = await _setup_org_and_employee(
        graphql_client, root_loen_org
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee_uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=datetime(2020, 1, 1),
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    receiver = call_args.kwargs["receiver"]
    message = call_args.kwargs["body"]
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert "Mick Jagger" in message


@pytest.mark.integration_test
async def test_terminated_manager_future_to_date_no_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """A manager with to_date in the future doesn't trigger an email."""
    org_unit_uuid, employee_uuid = await _setup_org_and_employee(
        graphql_client, root_loen_org
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee_uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=datetime(2090, 1, 1),
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_vacant_manager_sends_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """A vacant manager (no person, no to_date) with from_date in the past
    triggers an alert."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    org_unit = await graphql_client._testing__create_org_unit(
        name="Afdeling",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit.uuid,
        person=None,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=None,
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    message = email_client.send_email.call_args.kwargs["body"]
    assert "Vacant manager" in message


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "true"})
async def test_terminated_manager_use_org_unit_emails(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS is true, the alert is
    sent to the org unit's (institution ancestor) email address instead of
    the configured receivers."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _result = (await graphql_client._testing__get_org_unit_address_type()).objects[0]
    assert _result.current is not None
    org_unit_address_type = _result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    institution = await graphql_client._testing__create_org_unit(
        name="Institution",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await graphql_client._testing__create_org_unit_address(
        org_unit=institution.uuid,
        value="institution@example.com",
        address_type=org_unit_address_type,
        from_=datetime(2010, 1, 1),
    )

    child = await graphql_client._testing__create_org_unit(
        name="Afdeling",
        parent=institution.uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=child.uuid,
        person=employee.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=datetime(2020, 1, 1),
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    receiver = email_client.send_email.call_args.kwargs["receiver"]
    assert "institution@example.com" in receiver


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "true"})
async def test_terminated_manager_on_root_uses_root_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When use_org_unit_emails is true and the manager is on the root org unit,
    the email goes to the root's own address (get_org_unit_address path)."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _result = (await graphql_client._testing__get_org_unit_address_type()).objects[0]
    assert _result.current is not None
    org_unit_address_type = _result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    await graphql_client._testing__create_org_unit_address(
        org_unit=root_loen_org,
        value="root@example.com",
        address_type=org_unit_address_type,
        from_=datetime(2010, 1, 1),
    )

    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    # Manager directly on root org unit
    manager = await graphql_client._testing__create_manager(
        orgunit=root_loen_org,
        person=employee.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=datetime(2020, 1, 1),
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    receiver = email_client.send_email.call_args.kwargs["receiver"]
    assert "root@example.com" in receiver


@pytest.mark.integration_test
async def test_manager_with_multiple_validities_picks_correct_one(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When a manager has multiple validity periods (e.g. was updated),
    the handler picks the current or latest one via extract_current_or_latest_validity."""
    org_unit_uuid, employee_uuid = await _setup_org_and_employee(
        graphql_client, root_loen_org
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee_uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=None,
    )

    # Trivial update to create a second validity period.
    # The user_key change is irrelevant — we just need multiple validities
    # so extract_current_or_latest_validity has to pick one.
    await graphql_client._testing__update_manager(
        uuid=manager.uuid,
        from_=datetime(2018, 1, 1),
        to=None,
        person=employee_uuid,
        user_key="updated",
    )

    # Terminate in the past — ends the latest validity
    await graphql_client._testing__terminate_manager(
        uuid=manager.uuid,
        to=datetime(2020, 1, 1),
    )

    # extract_current_or_latest_validity picks from multiple validities.
    # The latest has to_date=2020-01-01 (in the past) → email is sent.
    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    message = email_client.send_email.call_args.kwargs["body"]
    assert "Mick Jagger" in message


@pytest.mark.integration_test
async def test_manager_with_multiple_validities_current_is_picked(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When a manager has multiple validities and one is currently active
    (open-ended), extract_current_or_latest_validity picks the current one
    and no email is sent because the manager is still employed."""
    org_unit_uuid, employee_uuid = await _setup_org_and_employee(
        graphql_client, root_loen_org
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee_uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=None,
    )

    # Update to create a second validity — manager is still active (no to_date)
    await graphql_client._testing__update_manager(
        uuid=manager.uuid,
        from_=datetime(2018, 1, 1),
        to=None,
        person=employee_uuid,
        user_key="updated",
    )

    # One validity is open-ended and in the past → is_current returns True for
    # it, and extract_current_or_latest_validity returns it (the manager is
    # currently employed, so no email).
    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_terminated_org_unit_skips_alert(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the manager's org unit has been terminated, get_org_unit_data
    returns None for the current state and the handler skips sending an alert."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    org_unit = await graphql_client._testing__create_org_unit(
        name="Terminated",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=datetime(2015, 1, 1),
    )

    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )

    # Vacant manager (no person) on a terminated org unit. The vacant branch
    # uses from_date as the effective to_date, so the handler proceeds past
    # the time check and then skips when the org unit's current state is None.
    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit.uuid,
        person=None,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2012, 1, 1),
        to=None,
    )

    await alert_on_manager_removal(context, manager.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


EXCLUDED_UUID = UUID("00000000-0000-0000-0000-000000000042")


async def _terminated_manager_in_org_unit(
    graphql_client: GraphQLClient, org_unit_uuid: UUID
) -> UUID:
    """Create a terminated manager in the given org unit; return the manager UUID."""
    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    manager_level = (await graphql_client._testing__get_manager_level()).objects[0].uuid
    manager_type = (await graphql_client._testing__get_manager_type()).objects[0].uuid
    responsibility = (
        (await graphql_client._testing__get_manager_responsibility()).objects[0].uuid
    )
    manager = await graphql_client._testing__create_manager(
        orgunit=org_unit_uuid,
        person=employee.uuid,
        manager_level=manager_level,
        manager_type=manager_type,
        responsibility=responsibility,
        from_=datetime(2015, 1, 1),
        to=datetime(2020, 1, 1),
    )
    return manager.uuid


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_EXCLUDE_ORG_UNITS": f'["{EXCLUDED_UUID}"]'})
async def test_excluded_ancestor_is_skipped(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the manager's org unit has an ancestor in the exclude list,
    no alert is sent."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="ExcludedRoot",
        root_uuid=EXCLUDED_UUID,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    child = await graphql_client._testing__create_org_unit(
        name="Child under excluded",
        parent=EXCLUDED_UUID,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )
    manager_uuid = await _terminated_manager_in_org_unit(graphql_client, child.uuid)

    await alert_on_manager_removal(context, manager_uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_EXCLUDE_ORG_UNITS": f'["{EXCLUDED_UUID}"]'})
async def test_excluded_direct_match_is_skipped(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the manager's own org unit UUID is in the exclude list,
    no alert is sent."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="ExcludedRoot",
        root_uuid=EXCLUDED_UUID,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    manager_uuid = await _terminated_manager_in_org_unit(graphql_client, EXCLUDED_UUID)

    await alert_on_manager_removal(context, manager_uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_EXCLUDE_ORG_UNITS": f'["{EXCLUDED_UUID}"]'})
async def test_exclude_list_set_but_no_match_sends_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When the exclude list is set but doesn't match the manager's org unit
    or any ancestor, the alert is still sent."""
    org_unit_uuid, _ = await _setup_org_and_employee(graphql_client, root_loen_org)
    manager_uuid = await _terminated_manager_in_org_unit(graphql_client, org_unit_uuid)

    await alert_on_manager_removal(context, manager_uuid, None, graphql_client)
    email_client.send_email.assert_called_once()
