"""Integration tests for inform_manager_on_employee_address_creation."""

from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from mo_smtp.agents import inform_manager_on_employee_address_creation
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_no_address(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the address UUID doesn't exist, no email is sent."""
    await inform_manager_on_employee_address_creation(
        context, uuid4(), None, graphql_client
    )
    email_client.send_email.assert_not_called()
