"""Integration tests for alert_on_ituser and alert_on_rolebinding."""

from datetime import datetime
from unittest.mock import MagicMock
from uuid import UUID

import pytest

from mo_smtp.agents import alert_on_ituser
from mo_smtp.autogenerated_graphql_client import GraphQLClient


async def _setup_ituser(
    graphql_client: GraphQLClient,
    user_key: str = "ADUSER-123",
) -> tuple[UUID, UUID]:
    """Create employee, IT system, IT user, role, and rolebinding.

    Returns (ituser_uuid, rolebinding_uuid).
    """
    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    itsystem = await graphql_client._testing__create_it_system(
        name="Active Directory",
        from_=datetime(2010, 1, 1),
    )
    ituser = await graphql_client._testing__create_it_user(
        itsystem=itsystem.uuid,
        person=employee.uuid,
        name=user_key,
        from_=datetime(2010, 1, 1),
        engagements=None,
    )

    role_facet = (await graphql_client._testing__get_role_facet()).objects[0].uuid
    role = await graphql_client._testing__create_class(
        name="admin",
        facet_uuid=role_facet,
        from_=datetime(2010, 1, 1),
    )
    rolebinding = await graphql_client._testing__create_rolebinding(
        ituser=ituser.uuid,
        role=role.uuid,
        from_=datetime(2010, 1, 1),
    )

    return ituser.uuid, rolebinding.uuid


@pytest.mark.integration_test
async def test_ituser_sends_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """An IT user event triggers an alert email."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    receiver = call_args.kwargs["receiver"]
    message = call_args.kwargs["body"]
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "Mick Jagger" in message
