"""Integration tests for the org unit relation alert flow (handle_org_unit)."""

from datetime import datetime
from unittest.mock import MagicMock
from uuid import UUID, uuid4

import pytest

from mo_smtp.agents import handle_org_unit
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_nonexistent_org_unit_no_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the org unit UUID doesn't exist, no email is sent."""
    await handle_org_unit(context, uuid4(), None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_org_unit_outside_loenorg_no_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """An org unit under a different root (not lønorganisation) is skipped."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    other_root = uuid4()
    await graphql_client._testing__create_org_unit_root(
        name="Administrationsorganisation",
        root_uuid=other_root,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    child = await graphql_client._testing__create_org_unit(
        name="Adm-enhed",
        parent=other_root,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await handle_org_unit(context, child.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_no_alert_when_org_unit_has_relation(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When an org unit has a relation to another org unit outside the
    lønorganisation (i.e. in the administrationsorganisation), no alert is sent."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Lønorganisation",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    adm_root = uuid4()
    await graphql_client._testing__create_org_unit_root(
        name="Administrationsorganisation",
        root_uuid=adm_root,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    loen_child = await graphql_client._testing__create_org_unit(
        name="Løn-enhed",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )
    adm_child = await graphql_client._testing__create_org_unit(
        name="Adm-enhed",
        parent=adm_root,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await graphql_client._testing__create_related_units(
        origin=loen_child.uuid,
        destination=[adm_child.uuid],
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await handle_org_unit(context, loen_child.uuid, None, graphql_client)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "true"})
async def test_sends_alert_to_org_unit_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When use_org_unit_emails is true, alert is sent to the org unit's
    institution email address."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _result = (await graphql_client._testing__get_org_unit_address_type()).objects[0]
    assert _result.current is not None
    org_unit_address_type = _result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Lønorganisation",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    institution = await graphql_client._testing__create_org_unit(
        name="Institution",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await graphql_client._testing__create_org_unit_address(
        org_unit=institution.uuid,
        value="institution@example.com",
        address_type=org_unit_address_type,
        from_=datetime(2010, 1, 1),
    )

    child = await graphql_client._testing__create_org_unit(
        name="Løn-enhed",
        parent=institution.uuid,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await handle_org_unit(context, child.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    assert email_client.send_email.call_args.kwargs["receiver"] == {
        "institution@example.com"
    }


@pytest.mark.integration_test
async def test_sends_alert_to_receivers(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When use_org_unit_emails is false (default), alert is sent to the
    configured receivers."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Lønorganisation",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    child = await graphql_client._testing__create_org_unit(
        name="Løn-enhed uden relation",
        parent=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
        to=None,
    )

    await handle_org_unit(context, child.uuid, None, graphql_client)

    email_client.send_email.assert_called_once()
    assert email_client.send_email.call_args.kwargs["receiver"] == {
        "datagruppen@silkeborg.dk"
    }


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "true"})
async def test_root_loenorg_uses_own_email(
    context,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
    root_loen_org: UUID,
):
    """When uuid == root_loen_org and use_org_unit_emails is true,
    the email is sent to the root org unit's own address."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    _result = (await graphql_client._testing__get_org_unit_address_type()).objects[0]
    assert _result.current is not None
    org_unit_address_type = _result.current.classes[0].uuid

    await graphql_client._testing__create_org_unit_root(
        name="Lønorganisation",
        root_uuid=root_loen_org,
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )

    await graphql_client._testing__create_org_unit_address(
        org_unit=root_loen_org,
        value="loenorg-root@example.com",
        address_type=org_unit_address_type,
        from_=datetime(2010, 1, 1),
    )

    await handle_org_unit(context, root_loen_org, None, graphql_client)

    email_client.send_email.assert_called_once()
    assert email_client.send_email.call_args.kwargs["receiver"] == {
        "loenorg-root@example.com"
    }
