import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.main import FastRAMQPI
from fastramqpi.ramqp.mo import MOAMQPSystem
from fastramqpi.ramqp.mo import MORouter

from mo_smtp import models
from .agents import amqp_router
from .autogenerated_graphql_client import GraphQLClient
from .config import Settings
from mo_smtp import mail

logger = structlog.get_logger()
fastapi_router = APIRouter()


def register_agents(
    amqp_router: MORouter,
    amqpsystem: MOAMQPSystem,
    agents_to_register: list[str],
):
    """
    Register agents so they listen to AMQP messages

    Only registers agents listed in agents_to_register
    """
    for registry_entry, routing_keys in amqp_router.registry.items():
        agent_name = registry_entry.__name__
        if agent_name in agents_to_register:
            amqpsystem.router.registry.update({registry_entry: routing_keys})


def create_app() -> FastAPI:
    """
    Initiate a FastRAMQPI instance.
    """

    logger.info("Import settings")
    settings = Settings()

    logger.info("FastRAMQPI setup")
    fastramqpi = FastRAMQPI(
        application_name="os2mo_email_listener",
        settings=settings.fastramqpi,
        graphql_version=25,
        graphql_client_cls=GraphQLClient,
        database_metadata=models.Base.metadata,
    )
    fastramqpi.add_context(settings=settings)

    email_client = mail.EmailClient(settings.email_settings)

    alert_service = mail.EmailAlert(
        sessionmaker=fastramqpi.get_context()["sessionmaker"],
        email_client=email_client,
        mo=fastramqpi.get_context()["graphql_client"],  # ??
        interval=settings.email_settings.interval,
        pre_notification_days=settings.email_settings.pre_notification_days,
    )
    fastramqpi.add_context(alert_service=alert_service)

    # Start alert service background loop
    alert_service.start()

    # FastAPI router
    app = fastramqpi.get_app()

    # MO AMQP
    mo_amqp_system = fastramqpi.get_amqpsystem()
    register_agents(amqp_router, mo_amqp_system, settings.active_agents)

    return app
