import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.main import FastRAMQPI
from fastramqpi.ramqp.mo import MOAMQPSystem
from fastramqpi.ramqp.mo import MORouter

from .agents import amqp_router
from .autogenerated_graphql_client import GraphQLClient
from .config import Settings
from .mail import EmailClient

logger = structlog.get_logger()
fastapi_router = APIRouter()


def register_agents(
    amqp_router: MORouter,
    amqpsystem: MOAMQPSystem,
    agents_to_register: list[str],
):
    """
    Register agents so they listen to AMQP messages

    Only registers agents listed in agents_to_register
    """
    for registry_entry, routing_keys in amqp_router.registry.items():
        agent_name = registry_entry.__name__
        if agent_name in agents_to_register:
            amqpsystem.router.registry.update({registry_entry: routing_keys})


def create_app() -> FastAPI:
    """
    Initiate a FastRAMQPI instance.
    """

    logger.info("Import settings")
    settings = Settings()

    logger.info("FastRAMQPI setup")
    fastramqpi = FastRAMQPI(
        application_name="os2mo_email_listener",
        settings=settings.fastramqpi,
        graphql_version=25,
        graphql_client_cls=GraphQLClient,
    )
    fastramqpi.add_context(settings=settings)

    email_client = EmailClient(settings.email_settings)

    fastapi_router = APIRouter()

    @fastapi_router.post("/send_test_email", status_code=202, tags=["Test"])
    async def send_test_mail(receiver: str):
        """
        Send a test email using the settings in config.py
        """
        email_client.send_email(
            receiver={receiver},
            subject="Test mail from OS2MO-smtp agent",
            body="If you see this mail, the test has succeeded",
            texttype="plain",
            allow_receiver_override=False,
        )

    app = fastramqpi.get_app()
    app.include_router(fastapi_router)

    logger.info("AMQP router setup")
    amqpsystem = fastramqpi.get_amqpsystem()
    register_agents(amqp_router, amqpsystem, settings.active_agents)

    return app
