# depends.py
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.depends import Session  # noqa: F401
from fastramqpi.ramqp.depends import from_context

from mo_smtp import mail
from .autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from .config import Settings as _Settings

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]

Settings = Annotated[_Settings, Depends(from_user_context("settings"))]

EmailAlert = Annotated[mail.EmailAlert, Depends(from_user_context("alert_service"))]
