# Generated by ariadne-codegen on 2025-02-20 12:55
# Source: queries.graphql

from typing import List, Optional

from .base_model import BaseModel


class GetInstitutionAddress(BaseModel):
    org_units: "GetInstitutionAddressOrgUnits"


class GetInstitutionAddressOrgUnits(BaseModel):
    objects: List["GetInstitutionAddressOrgUnitsObjects"]


class GetInstitutionAddressOrgUnitsObjects(BaseModel):
    current: Optional["GetInstitutionAddressOrgUnitsObjectsCurrent"]


class GetInstitutionAddressOrgUnitsObjectsCurrent(BaseModel):
    addresses: List["GetInstitutionAddressOrgUnitsObjectsCurrentAddresses"]


class GetInstitutionAddressOrgUnitsObjectsCurrentAddresses(BaseModel):
    value: str


GetInstitutionAddress.update_forward_refs()
GetInstitutionAddressOrgUnits.update_forward_refs()
GetInstitutionAddressOrgUnitsObjects.update_forward_refs()
GetInstitutionAddressOrgUnitsObjectsCurrent.update_forward_refs()
GetInstitutionAddressOrgUnitsObjectsCurrentAddresses.update_forward_refs()
