# Generated by ariadne-codegen on 2025-02-20 12:55
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnitRelations(BaseModel):
    org_units: "GetOrgUnitRelationsOrgUnits"


class GetOrgUnitRelationsOrgUnits(BaseModel):
    objects: List["GetOrgUnitRelationsOrgUnitsObjects"]


class GetOrgUnitRelationsOrgUnitsObjects(BaseModel):
    current: Optional["GetOrgUnitRelationsOrgUnitsObjectsCurrent"]


class GetOrgUnitRelationsOrgUnitsObjectsCurrent(BaseModel):
    name: str
    root: Optional[List["GetOrgUnitRelationsOrgUnitsObjectsCurrentRoot"]]
    engagements: List["GetOrgUnitRelationsOrgUnitsObjectsCurrentEngagements"]
    related_units: List["GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnits"]


class GetOrgUnitRelationsOrgUnitsObjectsCurrentRoot(BaseModel):
    uuid: UUID


class GetOrgUnitRelationsOrgUnitsObjectsCurrentEngagements(BaseModel):
    uuid: UUID


class GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnits(BaseModel):
    org_units: List["GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnits"]


class GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnits(BaseModel):
    uuid: UUID
    root: Optional[
        List["GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnitsRoot"]
    ]


class GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnitsRoot(BaseModel):
    uuid: UUID


GetOrgUnitRelations.update_forward_refs()
GetOrgUnitRelationsOrgUnits.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjects.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrent.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrentRoot.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrentEngagements.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnits.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnits.update_forward_refs()
GetOrgUnitRelationsOrgUnitsObjectsCurrentRelatedUnitsOrgUnitsRoot.update_forward_refs()
