# Generated by ariadne-codegen on 2024-12-02 10:43
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetManagerData(BaseModel):
    managers: "GetManagerDataManagers"


class GetManagerDataManagers(BaseModel):
    objects: List["GetManagerDataManagersObjects"]


class GetManagerDataManagersObjects(BaseModel):
    validities: List["GetManagerDataManagersObjectsValidities"]


class GetManagerDataManagersObjectsValidities(BaseModel):
    employee_uuid: Optional[UUID]
    org_unit_uuid: UUID
    validity: "GetManagerDataManagersObjectsValiditiesValidity"


class GetManagerDataManagersObjectsValiditiesValidity(BaseModel):
    to: Optional[datetime]
    from_: datetime = Field(alias="from")


GetManagerData.update_forward_refs()
GetManagerDataManagers.update_forward_refs()
GetManagerDataManagersObjects.update_forward_refs()
GetManagerDataManagersObjectsValidities.update_forward_refs()
GetManagerDataManagersObjectsValiditiesValidity.update_forward_refs()
