# Generated by ariadne-codegen on 2025-02-25 14:27
# Source: queries.graphql

from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetAddressData(BaseModel):
    addresses: "GetAddressDataAddresses"


class GetAddressDataAddresses(BaseModel):
    objects: list["GetAddressDataAddressesObjects"]


class GetAddressDataAddressesObjects(BaseModel):
    current: Optional["GetAddressDataAddressesObjectsCurrent"]


class GetAddressDataAddressesObjectsCurrent(BaseModel):
    name: str | None
    employee_uuid: UUID | None
    address_type: "GetAddressDataAddressesObjectsCurrentAddressType"


class GetAddressDataAddressesObjectsCurrentAddressType(BaseModel):
    scope: str | None


GetAddressData.update_forward_refs()
GetAddressDataAddresses.update_forward_refs()
GetAddressDataAddressesObjects.update_forward_refs()
GetAddressDataAddressesObjectsCurrent.update_forward_refs()
GetAddressDataAddressesObjectsCurrentAddressType.update_forward_refs()
