# Generated by ariadne-codegen on 2025-02-24 10:19
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class GetOrgUnitData(BaseModel):
    org_units: "GetOrgUnitDataOrgUnits"


class GetOrgUnitDataOrgUnits(BaseModel):
    objects: list["GetOrgUnitDataOrgUnitsObjects"]


class GetOrgUnitDataOrgUnitsObjects(BaseModel):
    validities: list["GetOrgUnitDataOrgUnitsObjectsValidities"]


class GetOrgUnitDataOrgUnitsObjectsValidities(BaseModel):
    name: str
    user_key: str
    parent_uuid: UUID | None
    managers: list["GetOrgUnitDataOrgUnitsObjectsValiditiesManagers"]


class GetOrgUnitDataOrgUnitsObjectsValiditiesManagers(BaseModel):
    employee_uuid: UUID | None


GetOrgUnitData.update_forward_refs()
GetOrgUnitDataOrgUnits.update_forward_refs()
GetOrgUnitDataOrgUnitsObjects.update_forward_refs()
GetOrgUnitDataOrgUnitsObjectsValidities.update_forward_refs()
GetOrgUnitDataOrgUnitsObjectsValiditiesManagers.update_forward_refs()
