# Generated by ariadne-codegen on 2023-08-17 13:58
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetAddressData(BaseModel):
    addresses: "GetAddressDataAddresses"


class GetAddressDataAddresses(BaseModel):
    objects: List["GetAddressDataAddressesObjects"]


class GetAddressDataAddressesObjects(BaseModel):
    current: Optional["GetAddressDataAddressesObjectsCurrent"]


class GetAddressDataAddressesObjectsCurrent(BaseModel):
    name: Optional[str]
    employee_uuid: Optional[UUID]
    address_type: "GetAddressDataAddressesObjectsCurrentAddressType"


class GetAddressDataAddressesObjectsCurrentAddressType(BaseModel):
    scope: Optional[str]


GetAddressData.update_forward_refs()
GetAddressDataAddresses.update_forward_refs()
GetAddressDataAddressesObjects.update_forward_refs()
GetAddressDataAddressesObjectsCurrent.update_forward_refs()
GetAddressDataAddressesObjectsCurrentAddressType.update_forward_refs()
