# Generated by ariadne-codegen on 2025-02-20 12:55
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnitData(BaseModel):
    org_units: "GetOrgUnitDataOrgUnits"


class GetOrgUnitDataOrgUnits(BaseModel):
    objects: List["GetOrgUnitDataOrgUnitsObjects"]


class GetOrgUnitDataOrgUnitsObjects(BaseModel):
    validities: List["GetOrgUnitDataOrgUnitsObjectsValidities"]


class GetOrgUnitDataOrgUnitsObjectsValidities(BaseModel):
    name: str
    user_key: str
    parent_uuid: Optional[UUID]
    managers: List["GetOrgUnitDataOrgUnitsObjectsValiditiesManagers"]


class GetOrgUnitDataOrgUnitsObjectsValiditiesManagers(BaseModel):
    employee_uuid: Optional[UUID]


GetOrgUnitData.update_forward_refs()
GetOrgUnitDataOrgUnits.update_forward_refs()
GetOrgUnitDataOrgUnitsObjects.update_forward_refs()
GetOrgUnitDataOrgUnitsObjectsValidities.update_forward_refs()
GetOrgUnitDataOrgUnitsObjectsValiditiesManagers.update_forward_refs()
