# Generated by ariadne-codegen on 2025-02-28 13:18
# Source: queries.graphql


from .base_model import BaseModel


class OrgUnitData(BaseModel):
    org_units: "OrgUnitDataOrgUnits"


class OrgUnitDataOrgUnits(BaseModel):
    objects: list["OrgUnitDataOrgUnitsObjects"]


class OrgUnitDataOrgUnitsObjects(BaseModel):
    validities: list["OrgUnitDataOrgUnitsObjectsValidities"]


class OrgUnitDataOrgUnitsObjectsValidities(BaseModel):
    name: str
    user_key: str


OrgUnitData.update_forward_refs()
OrgUnitDataOrgUnits.update_forward_refs()
OrgUnitDataOrgUnitsObjects.update_forward_refs()
OrgUnitDataOrgUnitsObjectsValidities.update_forward_refs()
