# Generated by ariadne-codegen on 2025-03-03 14:01
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class OrgUnitDescendants(BaseModel):
    org_units: "OrgUnitDescendantsOrgUnits"


class OrgUnitDescendantsOrgUnits(BaseModel):
    objects: list["OrgUnitDescendantsOrgUnitsObjects"]


class OrgUnitDescendantsOrgUnitsObjects(BaseModel):
    current: Optional["OrgUnitDescendantsOrgUnitsObjectsCurrent"]


class OrgUnitDescendantsOrgUnitsObjectsCurrent(BaseModel):
    name: str


OrgUnitDescendants.update_forward_refs()
OrgUnitDescendantsOrgUnits.update_forward_refs()
OrgUnitDescendantsOrgUnitsObjects.update_forward_refs()
OrgUnitDescendantsOrgUnitsObjectsCurrent.update_forward_refs()
