# Generated by ariadne-codegen on 2025-02-26 15:29
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class RootOrg(BaseModel):
    org: "RootOrgOrg"


class RootOrgOrg(BaseModel):
    uuid: UUID


RootOrg.update_forward_refs()
RootOrgOrg.update_forward_refs()
