# Generated by ariadne-codegen on 2025-03-21 11:35

from typing import Any
from collections.abc import Callable

SCALARS_PARSE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
SCALARS_SERIALIZE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
