# Generated by ariadne-codegen on 2025-02-26 16:28
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UserData(BaseModel):
    employees: "UserDataEmployees"


class UserDataEmployees(BaseModel):
    objects: list["UserDataEmployeesObjects"]


class UserDataEmployeesObjects(BaseModel):
    validities: list["UserDataEmployeesObjectsValidities"]


class UserDataEmployeesObjectsValidities(BaseModel):
    name: str
    addresses: list["UserDataEmployeesObjectsValiditiesAddresses"]
    engagements: list["UserDataEmployeesObjectsValiditiesEngagements"]


class UserDataEmployeesObjectsValiditiesAddresses(BaseModel):
    value: str
    address_type: "UserDataEmployeesObjectsValiditiesAddressesAddressType"


class UserDataEmployeesObjectsValiditiesAddressesAddressType(BaseModel):
    scope: str | None


class UserDataEmployeesObjectsValiditiesEngagements(BaseModel):
    org_unit_uuid: UUID


UserData.update_forward_refs()
UserDataEmployees.update_forward_refs()
UserDataEmployeesObjects.update_forward_refs()
UserDataEmployeesObjectsValidities.update_forward_refs()
UserDataEmployeesObjectsValiditiesAddresses.update_forward_refs()
UserDataEmployeesObjectsValiditiesAddressesAddressType.update_forward_refs()
UserDataEmployeesObjectsValiditiesEngagements.update_forward_refs()
