# Generated by ariadne-codegen on 2023-08-17 13:53
# Source: queries.graphql


from .base_model import BaseModel


class Version(BaseModel):
    version: "VersionVersion"


class VersionVersion(BaseModel):
    mo_version: str | None
    mo_hash: str | None


Version.update_forward_refs()
VersionVersion.update_forward_refs()
